// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listLocations: () => typedError<LocationTreeDto, AppErrorDto>(__TAURI_INVOKE("list_locations")),
	createRoom: (input: CreateRoomInput) => typedError<RoomDto, AppErrorDto>(__TAURI_INVOKE("create_room", { input })),
	createArea: (input: CreateAreaInput) => typedError<AreaDto, AppErrorDto>(__TAURI_INVOKE("create_area", { input })),
	listRacks: (areaId: string | null) => typedError<RackDto[], AppErrorDto>(__TAURI_INVOKE("list_racks", { areaId })),
	createRack: (input: CreateRackInput) => typedError<RackDto, AppErrorDto>(__TAURI_INVOKE("create_rack", { input })),
	listAssets: () => typedError<AssetDto[], AppErrorDto>(__TAURI_INVOKE("list_assets")),
	createAsset: (input: CreateAssetInput) => typedError<AssetDto, AppErrorDto>(__TAURI_INVOKE("create_asset", { input })),
	placeAsset: (input: PlaceAssetInput) => typedError<PlacementDto, AppErrorDto>(__TAURI_INVOKE("place_asset", { input })),
	getRackView: (areaId: string | null) => typedError<RackViewDto, AppErrorDto>(__TAURI_INVOKE("get_rack_view", { areaId })),
	seedDevData: () => typedError<SeedResultDto, AppErrorDto>(__TAURI_INVOKE("seed_dev_data")),
};

/* Types */
export type AppErrorDto = {
	code: string,
	message: string,
	details: ErrorDetailsDto | null,
	operationId: string,
};

export type AreaDto = {
	id: string,
	roomId: string,
	code: string,
	name: string,
	description: string | null,
	status: string,
};

export type AssetDto = {
	id: string,
	type: string,
	name: string,
	hostname: string | null,
	intranetIp: string | null,
	managementIp: string | null,
	serialNumber: string | null,
	vendor: string | null,
	model: string | null,
	purpose: string | null,
	heightU: number,
	status: string,
	notes: string | null,
	placement: AssetPlacementDto | null,
};

export type AssetPlacementDto = {
	placementId: string,
	rackId: string,
	rackCode: string,
	areaId: string,
	areaName: string,
	roomId: string,
	roomName: string,
	startU: number,
	endU: number,
};

export type CreateAreaInput = {
	roomId: string,
	code: string,
	name: string,
	description: string | null,
};

export type CreateAssetInput = {
	type: string,
	name: string,
	hostname: string | null,
	intranetIp: string | null,
	managementIp: string | null,
	serialNumber: string | null,
	vendor: string | null,
	model: string | null,
	purpose: string | null,
	heightU: number,
	status: string,
	notes: string | null,
};

export type CreateRackInput = {
	areaId: string,
	code: string,
	specification: string,
	totalU: number,
	powerCapacityW: number | null,
	notes: string | null,
};

export type CreateRoomInput = {
	code: string,
	name: string,
	description: string | null,
};

export type ErrorDetailsDto = {
	field: string | null,
	rackId: string | null,
	startU: number | null,
	endU: number | null,
	conflictingAssetId: string | null,
};

export type LocationTreeDto = {
	rooms: RoomNodeDto[],
};

export type PlaceAssetInput = {
	assetId: string,
	rackId: string,
	startU: number,
};

export type PlacementDto = {
	id: string,
	rackId: string,
	assetId: string,
	startU: number,
	endU: number,
	heightU: number,
	placedAt: string,
};

export type RackCanvasDto = {
	rack: RackDto,
	placements: RackPlacementViewDto[],
};

export type RackDto = {
	id: string,
	areaId: string,
	areaName: string,
	roomId: string,
	roomName: string,
	code: string,
	specification: string,
	totalU: number,
	powerCapacityW: number | null,
	status: string,
	notes: string | null,
};

export type RackPlacementViewDto = {
	placementId: string,
	assetId: string,
	name: string,
	type: string,
	status: string,
	hostname: string | null,
	intranetIp: string | null,
	serialNumber: string | null,
	vendor: string | null,
	model: string | null,
	purpose: string | null,
	startU: number,
	endU: number,
	heightU: number,
};

export type RackViewDto = {
	racks: RackCanvasDto[],
};

export type RoomDto = {
	id: string,
	code: string,
	name: string,
	description: string | null,
	status: string,
};

export type RoomNodeDto = {
	room: RoomDto,
	areas: AreaDto[],
};

export type SeedResultDto = {
	seeded: boolean,
	rooms: number,
	areas: number,
	racks: number,
	assets: number,
	placements: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
